# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                trust
local   keycloak        keycloak                                trust
local   forgejo         forgejo                                 trust
