# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                trust
local   keycloak        keycloak                                trust
local   forgejo         forgejo                                 trust
local   matrix-synapse  matrix-synapse                          trust
local   mas             mas                                     trust
local   wiki            wiki                                    trust